spring:
# 配置存储数据的mongoDB数据库连接
  data:
    mongodb:
      username: stock
      host: 127.0.0.1
      port: 27017
      password: 123456
      database: stock
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/stock?characterEncoding=utf8&serverTimezone=Asia/Shanghai&connectTimeout=30000
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 12345678
#    username: stock
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/stock?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: stock
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat
